# Generated by Django 5.2.6 on 2025-11-10 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanConturi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('simbol', models.CharField(blank=True, max_length=300, null=True)),
                ('analitic', models.CharField(blank=True, max_length=300, null=True)),
                ('denumire', models.CharField(blank=True, max_length=300, null=True)),
                ('tip', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('denumire', models.CharField(max_length=255, unique=True)),
                ('atribut', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cui', models.CharField(blank=True, max_length=10, null=True)),
                ('regcom', models.CharField(blank=True, max_length=50, null=True)),
                ('caen', models.CharField(blank=True, max_length=10, null=True)),
                ('cap_social', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('localitate', models.CharField(blank=True, max_length=100, null=True)),
                ('strada', models.CharField(blank=True, max_length=100, null=True)),
                ('numar', models.CharField(blank=True, max_length=10, null=True)),
                ('bloc', models.CharField(blank=True, max_length=10, null=True)),
                ('scara', models.CharField(blank=True, max_length=10, null=True)),
                ('ap', models.CharField(blank=True, max_length=10, null=True)),
                ('judet', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=10, null=True)),
                ('codpostal', models.CharField(blank=True, max_length=20, null=True)),
                ('telefon', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupurile acestui utilizator.', related_name='firma_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisiunile specifice acestui utilizator.', related_name='firma_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rapoarte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registru_jurnal', models.BooleanField(default=False)),
                ('balanta', models.BooleanField(default=False)),
                ('bilant', models.BooleanField(default=False)),
                ('analiza', models.BooleanField(default=False)),
                ('firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistruJurnal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feldoc', models.CharField(max_length=4)),
                ('nrdoc', models.PositiveIntegerField(editable=False)),
                ('datadoc', models.DateTimeField(auto_now_add=True)),
                ('explicatii', models.CharField(blank=True, max_length=100, null=True)),
                ('debit', models.CharField(max_length=15)),
                ('credit', models.CharField(max_length=15)),
                ('suma', models.DecimalField(decimal_places=2, max_digits=20)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registre_jurnale', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
