# Generated by Django 5.2.8 on 2025-11-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decorsoft', '0002_delete_rapoarte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrujurnal',
            name='feldoc',
            field=models.CharField(max_length=20),
        ),
    ]
