# Generated by Django 5.2.8 on 2025-11-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decorsoft', '0003_alter_registrujurnal_feldoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrujurnal',
            name='nrdoc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
