# Generated by Django 5.2.6 on 2025-11-15 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decorsoft', '0004_alter_registrujurnal_nrdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrujurnal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tva_children', to='decorsoft.registrujurnal'),
        ),
    ]
